on:
  push:
    branches: [master, release]
  pull_request:
  workflow_dispatch:

name: CI

env:
  CARGO_ARGS: --all-features --target i686-pc-windows-msvc --workspace
jobs:
  build:
    name: build
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
      - name: Set up the Windows environment
        shell: bash
        run: |
          choco install llvm openssl --x86
          echo "OPENSSL_DIR=C:\Program Files (x86)\OpenSSL-Win32" >>$GITHUB_ENV
          rustup target add i686-pc-windows-msvc
        if: runner.os == 'Windows'
      - uses: Swatinem/rust-cache@v1
      - name: build rustpython
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose ${{ env.CARGO_ARGS }}
      - name: Package Windows
        if: matrix.os == 'windows-latest'
        run: |
          New-Item -ItemType Directory -Path "package2333"
          Copy-Item -Path "target\release\*" -Destination "package2333" -Recurse
          7z a release.zip ./package2333/*
      - name: Upload Windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./release.zip
          name: windows.zip
